// Countries offered for the "Trending searches region" setting.
export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "India",
  "Ireland",
  "New Zealand",
  "South Africa",
  "Germany",
  "France",
  "Spain",
  "Italy",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Poland",
  "Portugal",
  "Greece",
  "Czech Republic",
  "Romania",
  "Hungary",
  "Mexico",
  "Brazil",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Philippines",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "United Arab Emirates",
  "Saudi Arabia",
  "Israel",
  "Turkey",
  "Nigeria",
  "Kenya",
];
